### PR TITLE
Fix Rust installation, as it's expecting confirmation (typing 'y') to…

### PR DESCRIPTION
**Pull request by patrocinio**
… proceed

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by joebaro — COMMENTED** [review]
We should not deviate from the official rust installation instructions. Skipping the installation prompts risks the user being unaware of what is being installed and if the rust installation script detects problems and presents warnings these might be ignored. This might also ignore important prompts added in the future as well.

That said, it is perfectly fine to adjust the explanatory text to mention that the user should follow the prompts and/or to add a hint (in text) that installation can be automated using `sh -s -- -y`, but we should not present that as the default.

**Comment by simonmarty** [comment]
We already provide a link to the Rust installation instructions right above these code lines. Based on Joe's comment, I'm going to go ahead and close this pull request.

**Comment by patrocinio** [comment]
@simonmarty and @joebaro I understand your point.
But the installation fails as it's documented.
If the user copies the two commands:
``
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
. "$HOME/.cargo/env"
``
as indicated in the instructions, the ". \"HOME..." will be pasted instead of the 'y'.
So the instruction needs to decouple these two lines.

**Comment by simonmarty** [comment]
Clarified it in https://github.com/aws/aws-secretsmanager-agent/pull/27

**Comment by joebaro** [comment]
Adding a `;` to the end of the sh line should also fix it.

**Pull request closed without merging**
